project_id = "eababvkyjfkhqmjkcxiy"

[functions.steam-auth]
verify_jwt = false

[functions.steam-profile]
verify_jwt = false

[functions.discord-notify]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.wayforpay-payment]
verify_jwt = false

[functions.nowpayments-payment]
verify_jwt = false

[functions.send-order-email]
verify_jwt = true

[functions.send-status-email]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-cart-reminder]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.send-broadcast]
verify_jwt = true

[functions.set-telegram-webhook]
verify_jwt = true

[functions.notify-ending-promotions]
verify_jwt = false

[functions.send-recommendations]
verify_jwt = true

[functions.send-promo-email]
verify_jwt = true
